# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 65d73790865e0856b0226b2ceb9cea3489bbc83db09cdb36da43b21874d5cdce2d63643905cc15be6a144b71b8e05c11297c09788a3205bf5fc5652de54da347

test:
  secret_key_base: 95d07b9ec166722ac73287f50dcac29f32685f311e0f8993e47f91919adaf47f089b4aef46b1ae09aef78d4e2a808811c96f01b8bfc2bfd0c02e6a3e7f8bd0e8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
